/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        tertiary: '#0a0054',
        'on-secondary-fixed': '#001a42',
        'secondary-fixed': '#d8e2ff',
        'surface-container': '#eeeeeb',
        'tertiary-fixed': '#e2dfff',
        'secondary-container': '#2170e4',
        'primary-fixed': '#d8e3fb',
        background: '#f9f9f6',
        'tertiary-container': '#18008f',
        'on-primary-fixed-variant': '#3c475a',
        'on-primary': '#ffffff',
        'surface-bright': '#f9f9f6',
        'secondary-fixed-dim': '#adc6ff',
        'surface-dim': '#dadad7',
        'on-secondary': '#ffffff',
        'inverse-primary': '#bcc7de',
        'surface-container-highest': '#e2e3e0',
        'on-secondary-fixed-variant': '#004395',
        'surface-tint': '#545f73',
        primary: '#091426',
        'on-secondary-container': '#fefcff',
        'on-tertiary-fixed': '#0f0069',
        outline: '#75777d',
        'primary-container': '#1e293b',
        'on-primary-fixed': '#111c2d',
        'surface-container-low': '#f4f4f1',
        'outline-variant': '#c5c6cd',
        'on-background': '#1a1c1b',
        secondary: '#0058be',
        'on-primary-container': '#8590a6',
        'on-surface-variant': '#45474c',
        'inverse-surface': '#2f312f',
        'error-container': '#ffdad6',
        'surface-variant': '#e2e3e0',
        'on-tertiary-fixed-variant': '#3323cc',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'inverse-on-surface': '#f1f1ee',
        'on-error-container': '#93000a',
        'surface-container-high': '#e8e8e5',
        'tertiary-fixed-dim': '#c3c0ff',
        surface: '#f9f9f6',
        'on-tertiary-container': '#8481ff',
        'on-surface': '#1a1c1b',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#bcc7de',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'space-md': '1rem',
        margin: '2.5rem',
        'space-sm': '0.5rem',
        'space-lg': '1.5rem',
        'margin-mobile': '1.25rem',
        'space-xl': '2.5rem',
        'space-xs': '0.25rem',
        gutter: '1.5rem',
        'gutter-mobile': '1rem',
      },
      fontFamily: {
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'code-sm': ['Inter', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-xl-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'code-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.96)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'grow-width': {
          from: { width: '0%' },
          to: { width: 'var(--target-width, 100%)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.5s ease-out both',
        'scale-in': 'scale-in 0.3s ease-out both',
      },
    },
  },
  plugins: [],
};
