"""initial schema: analyses and detections

Revision ID: 8189ede77515
Revises: 
Create Date: 2026-09-18 02:48:47.287106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8189ede77515'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_image_path', sa.String(length=512), nullable=False),
    sa.Column('annotated_image_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('processing_time', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('image_format', sa.String(length=16), nullable=False),
    sa.Column('objects_detected', sa.Integer(), nullable=False),
    sa.Column('average_confidence', sa.Float(), nullable=False),
    sa.Column('detection_model_name', sa.String(length=64), nullable=False),
    sa.Column('classification_model_name', sa.String(length=64), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('detection_enabled', sa.Boolean(), nullable=False),
    sa.Column('classification_enabled', sa.Boolean(), nullable=False),
    sa.Column('top_classifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('class_name', sa.String(length=64), nullable=False),
    sa.Column('detection_confidence', sa.Float(), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('classification_class_name', sa.String(length=128), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_analysis_id'), 'detections', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_analysis_id'), table_name='detections')
    op.drop_table('detections')
    op.drop_table('analyses')
    # ### end Alembic commands ###
